pip install xlrd
pip install textract
pip install spacy
pip install future
pip install pandas
pip install seaborn
pip install scikit-learn
pip install matplotlib
pip install numpy
pip install tensorflow
pip install inscriptis
